--liquibase formatted sql

--changeset recipe:0000_initial_setup
CREATE TABLE recipe (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(1000),
    servings INT
);

CREATE TABLE app_user (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL
);

CREATE TABLE role (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    recipe_id INT NOT NULL,
    role VARCHAR(25) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES app_user(id),
    FOREIGN KEY (recipe_id) REFERENCES recipe(id)
);

CREATE TABLE product (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    vegetarian BOOLEAN DEFAULT FALSE
);

CREATE TABLE ingredient (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id INT NOT NULL,
    product_id INT NOT NULL,
    amount VARCHAR(25),
    FOREIGN KEY (recipe_id) REFERENCES recipe(id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);