package nl.recipe.assignment.model.mapper;

import nl.recipe.assignment.model.dto.IngredientDto;
import nl.recipe.assignment.model.dto.ProductDto;
import nl.recipe.assignment.model.dto.RecipeDto;
import nl.recipe.assignment.model.dto.RecipeRequest;
import nl.recipe.assignment.model.dto.UserDto;
import nl.recipe.assignment.model.entity.AppUser;
import nl.recipe.assignment.model.entity.Ingredient;
import nl.recipe.assignment.model.entity.Product;
import nl.recipe.assignment.model.entity.Recipe;
import nl.recipe.assignment.model.entity.Role;
import nl.recipe.assignment.model.entity.RoleType;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import java.util.List;

@Mapper(componentModel = "spring")
public interface DomainMapper {

    @Mapping(target = "author", source = "roles")
    @Mapping(target = "contributors", source = "roles")
    RecipeDto toDto(Recipe recipe);

    List<RecipeDto> toRecipeDtoList(List<Recipe> recipes);

    // Roles and ingredients require custom logic when mapping and therefor are ignored here. The id will be generated by DB.
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "roles", ignore = true)
    @Mapping(target = "ingredients", ignore = true)
    Recipe toEntity(RecipeRequest request);

    IngredientDto toIngredientDto(Ingredient ingredient);

    ProductDto toProductDto(Product product);

    UserDto toDto(AppUser user);

    List<UserDto> toUserDtoList(List<AppUser> users);

    @Mapping(target = "id", ignore = true)
    AppUser toEntity(UserDto userDto);

    // Find the author from the role list.
    default UserDto authorFromRoles(List<Role> roles) {
        if (roles == null) {
            return null;
        }
        return roles.stream()
                .filter(role -> role.getRole() == RoleType.AUTHOR)
                .map(Role::getUser)
                .map(this::toDto)
                .findFirst()
                .orElse(null);
    }

    // Find the contributors from the role list (author excluded).
    default List<UserDto> contributorsFromRoles(List<Role> roles) {
        if (roles == null) {
            return List.of();
        }
        return roles.stream()
                .filter(role -> role.getRole() == RoleType.CONTRIBUTOR)
                .map(Role::getUser)
                .map(this::toDto)
                .toList();
    }
}
